-- ===============================================================================
-- Rename Views to New Naming Convention
-- ===============================================================================
-- VETL_*     - ETL Critical Views
-- VAPEXUI_*  - APEX UI Views  
-- VTEST_*    - Test Views
-- V_*        - General Reporting Views
-- ===============================================================================

SET SERVEROUTPUT ON

-- Rename APEX UI views
CREATE OR REPLACE VIEW VAPEXUI_ETL_HISTORY AS SELECT * FROM V_APEX_ETL_HISTORY;
DROP VIEW V_APEX_ETL_HISTORY;

CREATE OR REPLACE VIEW VAPEXUI_ETL_STATUS AS SELECT * FROM V_APEX_ETL_STATUS;
DROP VIEW V_APEX_ETL_STATUS;

CREATE OR REPLACE VIEW VAPEXUI_ISSUES_LOV AS SELECT * FROM V_APEX_ISSUES_LOV;
DROP VIEW V_APEX_ISSUES_LOV;

CREATE OR REPLACE VIEW VAPEXUI_PLANT_LOV AS SELECT * FROM V_APEX_PLANT_LOV;
DROP VIEW V_APEX_PLANT_LOV;

CREATE OR REPLACE VIEW VAPEXUI_PLANT_SELECTION AS SELECT * FROM V_APEX_PLANT_SELECTION;
DROP VIEW V_APEX_PLANT_SELECTION;

CREATE OR REPLACE VIEW VAPEXUI_AVAILABLE_PLANTS_LOV AS SELECT * FROM V_AVAILABLE_PLANTS_LOV;
DROP VIEW V_AVAILABLE_PLANTS_LOV;

CREATE OR REPLACE VIEW VAPEXUI_ETL_CONTROL_ISSUES_LOV AS SELECT * FROM V_ETL_CONTROL_ISSUES_LOV;
DROP VIEW V_ETL_CONTROL_ISSUES_LOV;

CREATE OR REPLACE VIEW VAPEXUI_ETL_CONTROL_PLANTS_LOV AS SELECT * FROM V_ETL_CONTROL_PLANTS_LOV;
DROP VIEW V_ETL_CONTROL_PLANTS_LOV;

-- Rename Test views
CREATE OR REPLACE VIEW VTEST_BY_FLOW_STEP AS SELECT * FROM V_TEST_BY_FLOW_STEP;
DROP VIEW V_TEST_BY_FLOW_STEP;

CREATE OR REPLACE VIEW VTEST_COVERAGE AS SELECT * FROM V_TEST_COVERAGE;
DROP VIEW V_TEST_COVERAGE;

CREATE OR REPLACE VIEW VTEST_FAILURES AS SELECT * FROM V_TEST_FAILURES;
DROP VIEW V_TEST_FAILURES;

CREATE OR REPLACE VIEW VTEST_FAILURE_ANALYSIS AS SELECT * FROM V_TEST_FAILURE_ANALYSIS;
DROP VIEW V_TEST_FAILURE_ANALYSIS;

CREATE OR REPLACE VIEW VTEST_SUMMARY AS SELECT * FROM V_TEST_SUMMARY;
DROP VIEW V_TEST_SUMMARY;

-- Keep these as V_ (general reporting)
-- V_ACTIVE_PLANT_SELECTIONS - keep as is
-- V_ETL_CONTROL_LOG - keep as is  
-- V_ETL_CONTROL_STATUS - keep as is

PROMPT
PROMPT View renaming complete!
PROMPT
-- Show final result
SELECT 
    view_name,
    CASE 
        WHEN view_name LIKE 'VETL_%' THEN 'ETL Critical'
        WHEN view_name LIKE 'VAPEXUI_%' THEN 'APEX UI'
        WHEN view_name LIKE 'VTEST_%' THEN 'Testing'
        WHEN view_name LIKE 'V_%' THEN 'General Reporting'
    END as view_category,
    status
FROM user_views
ORDER BY view_category, view_name;