SET SERVEROUTPUT ON

BEGIN
    PKG_ETL_TEST_UTILS.reset_for_testing;
    DBMS_OUTPUT.PUT_LINE('Database reset complete');
END;
/

-- Verify all tables are cleared
SELECT 'Reference Tables' as category FROM dual;
SELECT table_name, COUNT(*) as count 
FROM (
    SELECT 'PCS_REFERENCES' as table_name, COUNT(*) as count FROM PCS_REFERENCES
    UNION ALL SELECT 'VDS_REFERENCES', COUNT(*) FROM VDS_REFERENCES
    UNION ALL SELECT 'MDS_REFERENCES', COUNT(*) FROM MDS_REFERENCES
    UNION ALL SELECT 'EDS_REFERENCES', COUNT(*) FROM EDS_REFERENCES
    UNION ALL SELECT 'VSK_REFERENCES', COUNT(*) FROM VSK_REFERENCES
    UNION ALL SELECT 'ESK_REFERENCES', COUNT(*) FROM ESK_REFERENCES
    UNION ALL SELECT 'PIPE_ELEMENT_REFERENCES', COUNT(*) FROM PIPE_ELEMENT_REFERENCES
    UNION ALL SELECT 'SC_REFERENCES', COUNT(*) FROM SC_REFERENCES
    UNION ALL SELECT 'VSM_REFERENCES', COUNT(*) FROM VSM_REFERENCES
)
WHERE count > 0;

SELECT 'PCS Tables' as category FROM dual;
SELECT table_name, COUNT(*) as count 
FROM (
    SELECT 'PCS_LIST' as table_name, COUNT(*) as count FROM PCS_LIST
    UNION ALL SELECT 'PCS_HEADER_PROPERTIES', COUNT(*) FROM PCS_HEADER_PROPERTIES
    UNION ALL SELECT 'PCS_TEMP_PRESSURES', COUNT(*) FROM PCS_TEMP_PRESSURES
    UNION ALL SELECT 'PCS_PIPE_SIZES', COUNT(*) FROM PCS_PIPE_SIZES
    UNION ALL SELECT 'PCS_PIPE_ELEMENTS', COUNT(*) FROM PCS_PIPE_ELEMENTS
    UNION ALL SELECT 'PCS_VALVE_ELEMENTS', COUNT(*) FROM PCS_VALVE_ELEMENTS
    UNION ALL SELECT 'PCS_EMBEDDED_NOTES', COUNT(*) FROM PCS_EMBEDDED_NOTES
)
WHERE count > 0;

SELECT 'VDS Catalog' as category FROM dual;
SELECT 'VDS_LIST' as table_name, COUNT(*) as count FROM VDS_LIST WHERE ROWNUM = 1;

SELECT 'Audit Tables' as category FROM dual;
SELECT 'RAW_JSON' as table_name, COUNT(*) as count FROM RAW_JSON WHERE ROWNUM = 1;

SELECT 'Control Tables (should have data)' as category FROM dual;
SELECT 'ETL_FILTER' as table_name, COUNT(*) as count FROM ETL_FILTER
UNION ALL
SELECT 'CONTROL_SETTINGS', COUNT(*) FROM CONTROL_SETTINGS
UNION ALL
SELECT 'CONTROL_ENDPOINTS', COUNT(*) FROM CONTROL_ENDPOINTS;

EXIT;
