SET SERVEROUTPUT ON
SET LINESIZE 200

PROMPT ====================================
PROMPT Executing PKG_MAIN_ETL_CONTROL.run_main_etl
PROMPT ====================================

EXEC PKG_MAIN_ETL_CONTROL.run_main_etl;

PROMPT ====================================
PROMPT ETL Complete - Checking Results
PROMPT ====================================

SELECT 'PCS_REFERENCES' as table_name, COUNT(*) as records FROM PCS_REFERENCES
UNION ALL
SELECT 'VDS_REFERENCES', COUNT(*) FROM VDS_REFERENCES  
UNION ALL
SELECT 'MDS_REFERENCES', COUNT(*) FROM MDS_REFERENCES
UNION ALL
SELECT 'EDS_REFERENCES', COUNT(*) FROM EDS_REFERENCES
UNION ALL
SELECT 'VSK_REFERENCES', COUNT(*) FROM VSK_REFERENCES
UNION ALL
SELECT 'ESK_REFERENCES', COUNT(*) FROM ESK_REFERENCES
UNION ALL
SELECT 'PIPE_ELEMENT_REFERENCES', COUNT(*) FROM PIPE_ELEMENT_REFERENCES
UNION ALL
SELECT 'SC_REFERENCES', COUNT(*) FROM SC_REFERENCES
UNION ALL
SELECT 'VSM_REFERENCES', COUNT(*) FROM VSM_REFERENCES
UNION ALL
SELECT 'PCS_LIST', COUNT(*) FROM PCS_LIST
UNION ALL
SELECT 'PCS_HEADER_PROPERTIES', COUNT(*) FROM PCS_HEADER_PROPERTIES
UNION ALL
SELECT 'PCS_TEMP_PRESSURES', COUNT(*) FROM PCS_TEMP_PRESSURES
UNION ALL
SELECT 'PCS_PIPE_SIZES', COUNT(*) FROM PCS_PIPE_SIZES
UNION ALL
SELECT 'PCS_PIPE_ELEMENTS', COUNT(*) FROM PCS_PIPE_ELEMENTS
UNION ALL
SELECT 'PCS_VALVE_ELEMENTS', COUNT(*) FROM PCS_VALVE_ELEMENTS
UNION ALL
SELECT 'PCS_EMBEDDED_NOTES', COUNT(*) FROM PCS_EMBEDDED_NOTES
ORDER BY 1;

EXIT;
