-- Simple verification of reset
SELECT 'All Data Tables' as check_type, 
       SUM(cnt) as total_records 
FROM (
    SELECT COUNT(*) as cnt FROM PCS_REFERENCES
    UNION ALL SELECT COUNT(*) FROM VDS_REFERENCES
    UNION ALL SELECT COUNT(*) FROM MDS_REFERENCES
    UNION ALL SELECT COUNT(*) FROM EDS_REFERENCES
    UNION ALL SELECT COUNT(*) FROM VSK_REFERENCES
    UNION ALL SELECT COUNT(*) FROM ESK_REFERENCES
    UNION ALL SELECT COUNT(*) FROM PIPE_ELEMENT_REFERENCES
    UNION ALL SELECT COUNT(*) FROM SC_REFERENCES
    UNION ALL SELECT COUNT(*) FROM VSM_REFERENCES
    UNION ALL SELECT COUNT(*) FROM PCS_LIST
    UNION ALL SELECT COUNT(*) FROM PCS_HEADER_PROPERTIES
    UNION ALL SELECT COUNT(*) FROM PCS_TEMP_PRESSURES
    UNION ALL SELECT COUNT(*) FROM PCS_PIPE_SIZES
    UNION ALL SELECT COUNT(*) FROM PCS_PIPE_ELEMENTS
    UNION ALL SELECT COUNT(*) FROM PCS_VALVE_ELEMENTS
    UNION ALL SELECT COUNT(*) FROM PCS_EMBEDDED_NOTES
    UNION ALL SELECT COUNT(*) FROM VDS_LIST
    UNION ALL SELECT COUNT(*) FROM RAW_JSON
);

EXIT;
