-- ===============================================================================
-- RAW_JSON Table - Immutable API Response Storage
-- ===============================================================================

-- Drop if exists
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE RAW_JSON CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Create table
CREATE TABLE RAW_JSON (
    raw_json_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint_key        VARCHAR2(100),      
    plant_id            VARCHAR2(50),       
    issue_revision      VARCHAR2(50),       
    api_url             VARCHAR2(500),      
    response_json       CLOB,               
    response_hash       VARCHAR2(64),       
    api_call_timestamp  TIMESTAMP DEFAULT SYSTIMESTAMP,
    created_date        DATE DEFAULT SYSDATE NOT NULL,
    -- GUID columns for API correlation tracking
    transaction_guid    RAW(16) DEFAULT SYS_GUID(),
    correlation_id      VARCHAR2(36),  -- To link related API calls
    request_id          VARCHAR2(36),  -- From API request headers
    CONSTRAINT UK_RAW_JSON_HASH UNIQUE (response_hash)
);

-- Comments
COMMENT ON TABLE RAW_JSON IS 'Immutable storage of all API responses with SHA256 deduplication to prevent reprocessing';
COMMENT ON COLUMN RAW_JSON.raw_json_id IS 'Internal surrogate key';
COMMENT ON COLUMN RAW_JSON.endpoint_key IS 'API endpoint identifier (plants, issues, etc.)';
COMMENT ON COLUMN RAW_JSON.plant_id IS 'Plant ID if endpoint is plant-specific';
COMMENT ON COLUMN RAW_JSON.issue_revision IS 'Issue revision if endpoint is issue-specific';
COMMENT ON COLUMN RAW_JSON.api_url IS 'Full API URL that was called';
COMMENT ON COLUMN RAW_JSON.response_json IS 'Complete JSON response from API';
COMMENT ON COLUMN RAW_JSON.response_hash IS 'SHA256 hash for deduplication check';
COMMENT ON COLUMN RAW_JSON.api_call_timestamp IS 'When API was called';
COMMENT ON COLUMN RAW_JSON.created_date IS 'When record was inserted';
COMMENT ON COLUMN RAW_JSON.transaction_guid IS 'Unique identifier for this transaction';
COMMENT ON COLUMN RAW_JSON.correlation_id IS 'Links related API operations together';
COMMENT ON COLUMN RAW_JSON.request_id IS 'Request ID from API headers if provided';

-- Indexes
CREATE INDEX IDX_RAW_JSON_COMPOSITE ON RAW_JSON(endpoint_key, plant_id, api_call_timestamp);
CREATE INDEX IDX_RAW_JSON_TIMESTAMP ON RAW_JSON(api_call_timestamp);
CREATE INDEX IDX_RAW_JSON_ISSUE ON RAW_JSON(issue_revision);

PROMPT RAW_JSON table created successfully