-- ===============================================================================
-- Core Business Tables - TR2000 ETL System
-- ===============================================================================
-- Purpose: Main business entity tables (PLANTS, ISSUES, SELECTION_LOADER)
-- ===============================================================================

-- PLANTS: Master plant/facility table
CREATE TABLE PLANTS (
    plant_id                    VARCHAR2(50) PRIMARY KEY,
    operator_id                 NUMBER,
    operator_name               VARCHAR2(255),
    short_description           VARCHAR2(255),
    project                     VARCHAR2(255),
    long_description            VARCHAR2(4000),
    common_lib_plant_code       VARCHAR2(50),
    initial_revision            VARCHAR2(50),
    area_id                     NUMBER,
    area                        VARCHAR2(255),
    enable_embedded_note        CHAR(1) DEFAULT 'N' CHECK (enable_embedded_note IN ('Y', 'N')),
    category_id                 VARCHAR2(50),
    category                    VARCHAR2(255),
    document_space_link         VARCHAR2(500),
    enable_copy_pcs_from_plant  CHAR(1) DEFAULT 'N' CHECK (enable_copy_pcs_from_plant IN ('Y', 'N')),
    over_length                 CHAR(1) DEFAULT 'N' CHECK (over_length IN ('Y', 'N')),
    pcs_qa                      CHAR(1) DEFAULT 'N' CHECK (pcs_qa IN ('Y', 'N')),
    eds_mj                      CHAR(1) DEFAULT 'N' CHECK (eds_mj IN ('Y', 'N')),
    celsius_bar                 CHAR(1) DEFAULT 'N' CHECK (celsius_bar IN ('Y', 'N')),
    web_info_text               VARCHAR2(4000),
    bolt_tension_text           VARCHAR2(4000),
    visible                     CHAR(1) DEFAULT 'Y' CHECK (visible IN ('Y', 'N')),
    windows_remark_text         VARCHAR2(4000),
    user_protected              CHAR(1) DEFAULT 'N' CHECK (user_protected IN ('Y', 'N')),
    is_valid                    CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_valid IN ('Y', 'N')),
    created_date                DATE DEFAULT SYSDATE NOT NULL,
    last_modified_date          DATE DEFAULT SYSDATE NOT NULL,
    last_api_sync               TIMESTAMP,
    -- GUID columns for future REST API and multi-system integration
    plant_guid                  RAW(16) DEFAULT SYS_GUID(),
    external_guid               VARCHAR2(36),  -- If external system provides their GUID
    api_sync_guid               VARCHAR2(36)   -- For tracking API synchronization
);

COMMENT ON TABLE PLANTS IS 'Master table for all plants/facilities from TR2000 API. Uses soft delete pattern (is_valid flag)';
COMMENT ON COLUMN PLANTS.plant_id IS 'Unique identifier from TR2000 API (e.g., 124 for JSP2)';
COMMENT ON COLUMN PLANTS.short_description IS 'Short name/code for the plant (e.g., JSP2, GRANE)';
COMMENT ON COLUMN PLANTS.long_description IS 'Full descriptive name of the plant';
COMMENT ON COLUMN PLANTS.operator_name IS 'Company operating the plant (e.g., Equinor Europe)';
COMMENT ON COLUMN PLANTS.area IS 'Geographic or operational area';
COMMENT ON COLUMN PLANTS.is_valid IS 'Soft delete flag: Y=Active, N=Deleted/Inactive';
COMMENT ON COLUMN PLANTS.created_date IS 'When record was first created';
COMMENT ON COLUMN PLANTS.last_modified_date IS 'Last update from API or manual change';
COMMENT ON COLUMN PLANTS.plant_guid IS 'Globally unique identifier (GUID) for multi-system integration';
COMMENT ON COLUMN PLANTS.external_guid IS 'GUID from external system if provided';
COMMENT ON COLUMN PLANTS.api_sync_guid IS 'GUID for tracking API synchronization operations';

CREATE INDEX IDX_PLANTS_VALID ON PLANTS(is_valid);
CREATE INDEX IDX_PLANTS_OPERATOR ON PLANTS(operator_name);
CREATE INDEX IDX_PLANTS_AREA ON PLANTS(area);
CREATE UNIQUE INDEX UK_PLANTS_GUID ON PLANTS(plant_guid);
-- Add unique constraint for foreign key support
ALTER TABLE PLANTS ADD CONSTRAINT UK_PLANTS_GUID_CONST UNIQUE (plant_guid);

-- ISSUES: Issue revisions for plants
CREATE TABLE ISSUES (
    issue_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plant_id            VARCHAR2(50) NOT NULL,
    issue_revision      VARCHAR2(50) NOT NULL,
    status              VARCHAR2(50),
    rev_date            DATE,
    protect_status      VARCHAR2(50),
    general_revision    VARCHAR2(50),
    general_rev_date    DATE,
    pcs_revision        VARCHAR2(50),
    pcs_rev_date        DATE,
    eds_revision        VARCHAR2(50),
    eds_rev_date        DATE,
    vds_revision        VARCHAR2(50),
    vds_rev_date        DATE,
    vsk_revision        VARCHAR2(50),
    vsk_rev_date        DATE,
    mds_revision        VARCHAR2(50),
    mds_rev_date        DATE,
    esk_revision        VARCHAR2(50),
    esk_rev_date        DATE,
    sc_revision         VARCHAR2(50),
    sc_rev_date         DATE,
    vsm_revision        VARCHAR2(50),
    vsm_rev_date        DATE,
    user_name           VARCHAR2(255),
    user_entry_time     TIMESTAMP,
    user_protected      CHAR(1) DEFAULT 'N' CHECK (user_protected IN ('Y', 'N')),
    is_valid            CHAR(1) DEFAULT 'Y' NOT NULL CHECK (is_valid IN ('Y', 'N')),
    created_date        DATE DEFAULT SYSDATE NOT NULL,
    last_modified_date  DATE DEFAULT SYSDATE NOT NULL,
    last_api_sync       TIMESTAMP,
    -- GUID columns for future REST API and multi-system integration
    issue_guid          RAW(16) DEFAULT SYS_GUID(),
    external_guid       VARCHAR2(36),
    api_sync_guid       VARCHAR2(36),
    CONSTRAINT UK_ISSUES UNIQUE (plant_id, issue_revision),
    CONSTRAINT FK_ISSUES_PLANT FOREIGN KEY (plant_id) REFERENCES PLANTS(plant_id)
);

COMMENT ON TABLE ISSUES IS 'Issue revisions for each plant with version control and multiple revision types (PCS, VDS, SC, etc.)';
COMMENT ON COLUMN ISSUES.issue_id IS 'Internal surrogate key';
COMMENT ON COLUMN ISSUES.plant_id IS 'Foreign key to PLANTS table';
COMMENT ON COLUMN ISSUES.issue_revision IS 'Issue version identifier (e.g., 1.0, 2.1, 3.3)';
COMMENT ON COLUMN ISSUES.status IS 'Issue status: S=Submitted, R=Reviewed, O=Open, M=Modified';
COMMENT ON COLUMN ISSUES.rev_date IS 'Main revision date';
COMMENT ON COLUMN ISSUES.pcs_revision IS 'Piping Class Specification revision number';
COMMENT ON COLUMN ISSUES.vds_revision IS 'Valve Datasheet revision number';
COMMENT ON COLUMN ISSUES.sc_revision IS 'Special Components revision number';
COMMENT ON COLUMN ISSUES.is_valid IS 'Soft delete flag: Y=Active, N=Deleted/Inactive';
COMMENT ON COLUMN ISSUES.issue_guid IS 'Globally unique identifier (GUID) for multi-system integration';
COMMENT ON COLUMN ISSUES.external_guid IS 'GUID from external system if provided';
COMMENT ON COLUMN ISSUES.api_sync_guid IS 'GUID for tracking API synchronization operations';

CREATE INDEX IDX_ISSUES_PLANT ON ISSUES(plant_id);
CREATE INDEX IDX_ISSUES_VALID ON ISSUES(is_valid);
CREATE INDEX IDX_ISSUES_STATUS ON ISSUES(status);
CREATE INDEX IDX_ISSUES_REV ON ISSUES(issue_revision);
CREATE UNIQUE INDEX UK_ISSUES_GUID ON ISSUES(issue_guid);
-- Add unique constraint for foreign key support
ALTER TABLE ISSUES ADD CONSTRAINT UK_ISSUES_GUID_CONST UNIQUE (issue_guid);

-- SELECTED_PLANTS: Tracks which plants are selected for ETL processing
CREATE TABLE SELECTED_PLANTS (
    plant_id            VARCHAR2(50) NOT NULL,
    is_active           CHAR(1) DEFAULT 'Y' NOT NULL,
    selected_by         VARCHAR2(50),
    selection_date      DATE DEFAULT SYSDATE,
    last_refresh        TIMESTAMP,
    plant_guid          RAW(16),
    api_correlation_id  VARCHAR2(36),
    CONSTRAINT PK_SELECTED_PLANTS PRIMARY KEY (plant_id),
    CONSTRAINT CHK_SEL_PLANT_ACTIVE CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT FK_SELECTED_PLANT_GUID FOREIGN KEY (plant_guid) REFERENCES PLANTS(plant_guid)
);

CREATE INDEX IDX_SEL_PLANTS_ACTIVE ON SELECTED_PLANTS(is_active);
CREATE INDEX IDX_SEL_PLANTS_GUID ON SELECTED_PLANTS(plant_guid);

COMMENT ON TABLE SELECTED_PLANTS IS 'Plants selected for ETL processing';
COMMENT ON COLUMN SELECTED_PLANTS.plant_id IS 'Plant identifier (primary key)';
COMMENT ON COLUMN SELECTED_PLANTS.is_active IS 'Y=Selected for processing, N=Deselected';
COMMENT ON COLUMN SELECTED_PLANTS.selected_by IS 'User who selected this plant';
COMMENT ON COLUMN SELECTED_PLANTS.selection_date IS 'When plant was first selected';
COMMENT ON COLUMN SELECTED_PLANTS.last_refresh IS 'Last time plant data was refreshed from API';
COMMENT ON COLUMN SELECTED_PLANTS.plant_guid IS 'Link to PLANTS table';

-- SELECTED_ISSUES: Tracks which issues within selected plants are chosen for ETL
CREATE TABLE SELECTED_ISSUES (
    plant_id            VARCHAR2(50) NOT NULL,
    issue_revision      VARCHAR2(50) NOT NULL,
    is_active           CHAR(1) DEFAULT 'Y' NOT NULL,
    selected_by         VARCHAR2(50),
    selection_date      DATE DEFAULT SYSDATE,
    last_etl_run        TIMESTAMP,
    etl_status          VARCHAR2(50),
    issue_guid          RAW(16),
    reference_count     NUMBER DEFAULT 0,
    api_correlation_id  VARCHAR2(36),
    -- Throttling columns to prevent excessive API calls
    last_ref_refresh_all TIMESTAMP,     -- When all references were last refreshed
    last_ref_refresh_pcs TIMESTAMP,     -- When PCS specifically was refreshed
    refresh_count       NUMBER DEFAULT 0, -- How many times refreshed today
    CONSTRAINT PK_SELECTED_ISSUES PRIMARY KEY (plant_id, issue_revision),
    CONSTRAINT CHK_SEL_ISSUE_ACTIVE CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT FK_SEL_ISSUE_PLANT FOREIGN KEY (plant_id) REFERENCES SELECTED_PLANTS(plant_id),
    CONSTRAINT FK_SELECTED_ISSUE_GUID FOREIGN KEY (issue_guid) REFERENCES ISSUES(issue_guid)
);

CREATE INDEX IDX_SEL_ISSUES_ACTIVE ON SELECTED_ISSUES(is_active);
CREATE INDEX IDX_SEL_ISSUES_PLANT ON SELECTED_ISSUES(plant_id);
CREATE INDEX IDX_SEL_ISSUES_GUID ON SELECTED_ISSUES(issue_guid);

COMMENT ON TABLE SELECTED_ISSUES IS 'Issues within selected plants chosen for ETL processing';
COMMENT ON COLUMN SELECTED_ISSUES.plant_id IS 'Plant this issue belongs to';
COMMENT ON COLUMN SELECTED_ISSUES.issue_revision IS 'Issue revision identifier';
COMMENT ON COLUMN SELECTED_ISSUES.is_active IS 'Y=Selected for processing, N=Deselected';
COMMENT ON COLUMN SELECTED_ISSUES.selected_by IS 'User who selected this issue';
COMMENT ON COLUMN SELECTED_ISSUES.selection_date IS 'When issue was first selected';
COMMENT ON COLUMN SELECTED_ISSUES.last_etl_run IS 'Last time ETL ran for this issue';
COMMENT ON COLUMN SELECTED_ISSUES.etl_status IS 'Status of last ETL run';
COMMENT ON COLUMN SELECTED_ISSUES.issue_guid IS 'Link to ISSUES table';
COMMENT ON COLUMN SELECTED_ISSUES.reference_count IS 'Total number of references loaded';