-- ===============================================================================
-- ETL Control Tables - TR2000 ETL System
-- ===============================================================================
-- Purpose: Configuration and control tables for ETL processing
-- ===============================================================================

-- CONTROL_ENDPOINTS: Configuration for API endpoints
CREATE TABLE CONTROL_ENDPOINTS (
    endpoint_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint_key        VARCHAR2(100) NOT NULL UNIQUE,
    endpoint_url        VARCHAR2(500),
    endpoint_type       VARCHAR2(50),  -- MASTER, DETAIL, REFERENCE
    parent_endpoint     VARCHAR2(100),
    processing_order    NUMBER,
    is_active           CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N')),
    requires_selection  CHAR(1) DEFAULT 'N' CHECK (requires_selection IN ('Y', 'N')),
    parse_package       VARCHAR2(100),
    parse_procedure     VARCHAR2(100),
    upsert_package      VARCHAR2(100),
    upsert_procedure    VARCHAR2(100),
    created_date        DATE DEFAULT SYSDATE
);

COMMENT ON TABLE CONTROL_ENDPOINTS IS 'Configuration for all API endpoints with processing rules and dependencies';

CREATE INDEX IDX_ENDPOINTS_ACTIVE ON CONTROL_ENDPOINTS(is_active);
CREATE INDEX IDX_ENDPOINTS_ORDER ON CONTROL_ENDPOINTS(processing_order);

-- ETL_STATS: Tracks endpoint statistics and monitoring data
CREATE TABLE ETL_STATS (
    state_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint_key        VARCHAR2(100) NOT NULL,
    plant_id            VARCHAR2(50),
    last_successful_run TIMESTAMP,
    last_response_hash  VARCHAR2(64),
    last_error          VARCHAR2(4000),
    retry_count         NUMBER DEFAULT 0,
    is_locked           CHAR(1) DEFAULT 'N' CHECK (is_locked IN ('Y', 'N')),
    locked_by           VARCHAR2(50),
    locked_date         TIMESTAMP,
    -- New monitoring columns
    api_call_count      NUMBER DEFAULT 0,
    total_response_time_ms NUMBER DEFAULT 0,
    avg_response_time_ms NUMBER GENERATED ALWAYS AS 
        (CASE WHEN api_call_count > 0 
              THEN ROUND(total_response_time_ms/api_call_count,2) 
              ELSE 0 END) VIRTUAL,
    min_response_time_ms NUMBER,
    max_response_time_ms NUMBER,
    success_count       NUMBER DEFAULT 0,
    failure_count       NUMBER DEFAULT 0,
    success_rate_pct    NUMBER GENERATED ALWAYS AS
        (CASE WHEN (success_count + failure_count) > 0
              THEN ROUND(100 * success_count/(success_count + failure_count),2)
              ELSE 0 END) VIRTUAL,
    last_5_durations    VARCHAR2(500),
    data_volume_mb      NUMBER,
    last_error_code     NUMBER,
    CONSTRAINT UK_ETL_STATS UNIQUE (endpoint_key, plant_id)
);

COMMENT ON TABLE ETL_STATS IS 'Tracks ETL statistics and monitoring data for each endpoint';

CREATE INDEX IDX_STATS_ENDPOINT ON ETL_STATS(endpoint_key);
CREATE INDEX IDX_STATS_LOCKED ON ETL_STATS(is_locked);

-- CONTROL_SETTINGS: System configuration
CREATE TABLE CONTROL_SETTINGS (
    setting_key         VARCHAR2(100) PRIMARY KEY,
    setting_value       VARCHAR2(4000),
    setting_type        VARCHAR2(50),  -- URL, NUMBER, STRING, BOOLEAN
    description         VARCHAR2(4000),
    is_encrypted        CHAR(1) DEFAULT 'N' CHECK (is_encrypted IN ('Y', 'N')),
    created_date        DATE DEFAULT SYSDATE,
    modified_date       DATE DEFAULT SYSDATE,
    modified_by         VARCHAR2(50)
);

COMMENT ON TABLE CONTROL_SETTINGS IS 'System-wide configuration settings (API URL, timeouts, retention policies)';