-- ===============================================================================
-- CASCADE_LOG Table - Audit Trail for Cascade Operations
-- ===============================================================================
-- Purpose: Track all cascade operations triggered by data changes
-- Used to prevent infinite loops and provide audit trail
-- ===============================================================================

CREATE TABLE CASCADE_LOG (
    cascade_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cascade_type        VARCHAR2(50),  -- DEACTIVATION, REACTIVATION, etc.
    source_table        VARCHAR2(50),  -- Table that initiated cascade
    source_id           VARCHAR2(100), -- ID of record that changed
    target_table        VARCHAR2(50),  -- Table being updated by cascade
    affected_count      NUMBER,         -- Number of records affected
    cascade_timestamp   TIMESTAMP DEFAULT SYSTIMESTAMP,
    cascade_session_id  VARCHAR2(100), -- Unique session to detect loops
    trigger_name        VARCHAR2(100), -- Which trigger fired
    action_taken        VARCHAR2(4000) -- Description of cascade action
);

-- Index for performance
CREATE INDEX IDX_CASCADE_LOG_SESSION ON CASCADE_LOG(cascade_session_id);
CREATE INDEX IDX_CASCADE_LOG_TIMESTAMP ON CASCADE_LOG(cascade_timestamp);

COMMENT ON TABLE CASCADE_LOG IS 'Audit trail for all cascade operations. Used to track data changes and prevent infinite loops.';
COMMENT ON COLUMN CASCADE_LOG.cascade_session_id IS 'Unique identifier for cascade session - prevents infinite loops';
COMMENT ON COLUMN CASCADE_LOG.trigger_name IS 'Name of trigger that initiated this cascade';

PROMPT CASCADE_LOG table created for cascade audit trail