-- ============================================================================
-- File: 01_test_tables.sql
-- Purpose: Create testing infrastructure tables for ETL validation
-- Author: TR2000 ETL Team
-- Date: 2025-08-24
-- ============================================================================

-- Drop existing test tables if they exist
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN ('TEST_RESULTS', 'TEMP_TEST_DATA')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- ============================================================================
-- TEST_RESULTS: Stores test execution results
-- ============================================================================
CREATE TABLE TEST_RESULTS (
    test_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_name VARCHAR2(100) NOT NULL,
    run_date DATE DEFAULT SYSDATE NOT NULL,
    status VARCHAR2(20) NOT NULL,
    error_msg VARCHAR2(4000),
    execution_time_ms NUMBER,
    test_suite VARCHAR2(50) DEFAULT 'CORE',
    CONSTRAINT chk_test_status CHECK (status IN ('PASS', 'FAIL', 'ERROR', 'SKIP'))
);

-- Add comments
COMMENT ON TABLE TEST_RESULTS IS 'Stores results from PKG_SIMPLE_TESTS executions';
COMMENT ON COLUMN TEST_RESULTS.test_id IS 'Auto-generated test result ID';
COMMENT ON COLUMN TEST_RESULTS.test_name IS 'Name of the test function executed';
COMMENT ON COLUMN TEST_RESULTS.run_date IS 'Timestamp when test was executed';
COMMENT ON COLUMN TEST_RESULTS.status IS 'Test outcome: PASS, FAIL, ERROR, or SKIP';
COMMENT ON COLUMN TEST_RESULTS.error_msg IS 'Details about failure or error if applicable';
COMMENT ON COLUMN TEST_RESULTS.execution_time_ms IS 'Test execution duration in milliseconds';
COMMENT ON COLUMN TEST_RESULTS.test_suite IS 'Grouping for test categories (CORE, REFERENCE, PCS, etc.)';

-- Create index for quick lookups
CREATE INDEX idx_test_results_date ON TEST_RESULTS(run_date DESC);
CREATE INDEX idx_test_results_status ON TEST_RESULTS(status, run_date DESC);

-- ============================================================================
-- TEMP_TEST_DATA: Temporary storage for test data generation
-- ============================================================================
CREATE TABLE TEMP_TEST_DATA (
    data_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_type VARCHAR2(50) NOT NULL,
    data_key VARCHAR2(100) NOT NULL,
    data_value CLOB,
    created_date DATE DEFAULT SYSDATE,
    CONSTRAINT uk_test_data UNIQUE (data_type, data_key)
);

COMMENT ON TABLE TEMP_TEST_DATA IS 'Temporary storage for test JSON responses and mock data';
COMMENT ON COLUMN TEMP_TEST_DATA.data_type IS 'Type of test data (PLANT_JSON, ISSUE_JSON, etc.)';
COMMENT ON COLUMN TEMP_TEST_DATA.data_key IS 'Unique identifier for this test data';
COMMENT ON COLUMN TEMP_TEST_DATA.data_value IS 'JSON or other test data content';

-- ============================================================================
-- Create view for test summary
-- ============================================================================
CREATE OR REPLACE VIEW V_TEST_SUMMARY AS
SELECT 
    test_suite,
    COUNT(*) as total_tests,
    SUM(CASE WHEN status = 'PASS' THEN 1 ELSE 0 END) as passed,
    SUM(CASE WHEN status = 'FAIL' THEN 1 ELSE 0 END) as failed,
    SUM(CASE WHEN status = 'ERROR' THEN 1 ELSE 0 END) as errors,
    SUM(CASE WHEN status = 'SKIP' THEN 1 ELSE 0 END) as skipped,
    ROUND(100 * SUM(CASE WHEN status = 'PASS' THEN 1 ELSE 0 END) / COUNT(*), 1) as pass_rate,
    MAX(run_date) as last_run
FROM TEST_RESULTS
WHERE run_date >= TRUNC(SYSDATE)  -- Today's tests only
GROUP BY test_suite;

COMMENT ON VIEW V_TEST_SUMMARY IS 'Summary of test results by suite for current day';

-- ============================================================================
-- Create view for recent failures
-- ============================================================================
CREATE OR REPLACE VIEW V_TEST_FAILURES AS
SELECT 
    test_name,
    status,
    error_msg,
    run_date,
    execution_time_ms
FROM TEST_RESULTS
WHERE status IN ('FAIL', 'ERROR')
  AND run_date >= SYSDATE - 7  -- Last 7 days
ORDER BY run_date DESC;

COMMENT ON VIEW V_TEST_FAILURES IS 'Recent test failures and errors for debugging';

PROMPT
PROMPT Test infrastructure tables created successfully:
PROMPT - TEST_RESULTS: Store test execution results
PROMPT - TEMP_TEST_DATA: Store temporary test data
PROMPT - V_TEST_SUMMARY: View test summary by suite
PROMPT - V_TEST_FAILURES: View recent failures
PROMPT